vim.keymap.set("i", "jk", "<Esc>")
vim.keymap.set("n", "U", "<C-r>", { desc = "Redo", noremap = true, silent = true })
vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "k", "gk")
vim.keymap.set("n", "gl", vim.diagnostic.open_float, { desc = "Open diagnostic float" })
